(() => {
'use strict';
const $=s=>document.querySelector(s);
const ui={scene:$('#scene'),previewPanel:$('#previewPanel'),resultPanel:$('#resultPanel'),previewRounds:$('#previewRounds'),rerollBtn:$('#rerollBtn'),startBtn:$('#startBtn'),againBtn:$('#againBtn'),stakeInput:$('#stakeInput'),stakeMinus:$('#stakeMinus'),stakePlus:$('#stakePlus'),routeButtons:$('#routeButtons'),routeField:$('#routeField'),defendersLayer:$('#defendersLayer'),timerWrap:$('#timerWrap'),timerBar:$('#timerBar'),timerText:$('#timerText'),message:$('#message'),stakeHud:$('#stakeHud'),multiplierHud:$('#multiplierHud'),potentialHud:$('#potentialHud'),roundLabel:$('#roundLabel'),stageCount:$('#stageCount'),soundBtn:$('#soundBtn'),resultTitle:$('#resultTitle'),resultBody:$('#resultBody'),resultStake:$('#resultStake'),resultOdds:$('#resultOdds'),resultWin:$('#resultWin'),cinematic:$('#cinematic'),frameA:$('#cineFrameA'),frameB:$('#cineFrameB'),cineTitle:$('#cineTitle'),impactFlash:$('#impactFlash'),fx:$('#fxCanvas')};
const ctx=ui.fx.getContext('2d');
const TYPES={weak:{label:'弱',en:'WEAK',color:'#55ee84',singleOdds:1.20,img:'assets/defender_weak.png'},normal:{label:'普通',en:'NORMAL',color:'#ffd653',singleOdds:1.40,img:'assets/defender_normal.png'},strong:{label:'強',en:'STRONG',color:'#ff566f',singleOdds:1.60,img:'assets/defender_strong.png'}};
const KEYS=Object.keys(TYPES),RTP=.94,CHOICE_SECONDS=7;
const state={pack:[],round:0,stake:100,multiplier:1,playing:false,locked:false,timerId:null,timerStart:0,sound:true,particles:[],raf:0};
const rand=()=>{if(crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}return Math.random()};
const pick=a=>a[Math.floor(rand()*a.length)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round2=n=>Math.round(n*100)/100,money=n=>Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function laneSet(ds){if(ds.length===2){const a=TYPES[ds[0].type].singleOdds,b=TYPES[ds[1].type].singleOdds;return[{name:'LEFT',arrow:'↖',x:.18,odds:a,guards:[0]},{name:'MIDDLE',arrow:'↑',x:.50,odds:round2(1+(a-1)+(b-1)+.20),guards:[0,1]},{name:'RIGHT',arrow:'↗',x:.82,odds:b,guards:[1]}]}const a=TYPES[ds[0].type].singleOdds,b=TYPES[ds[1].type].singleOdds,c=TYPES[ds[2].type].singleOdds;return[{name:'FAR LEFT',arrow:'↖',x:.12,odds:a,guards:[0]},{name:'LEFT GAP',arrow:'↖',x:.38,odds:round2(1+(a-1)+(b-1)+.18),guards:[0,1]},{name:'RIGHT GAP',arrow:'↗',x:.62,odds:round2(1+(b-1)+(c-1)+.18),guards:[1,2]},{name:'FAR RIGHT',arrow:'↗',x:.88,odds:c,guards:[2]}]}
function makeRound(){const count=rand()<.56?2:3;const defenders=Array.from({length:count},()=>({type:pick(KEYS)}));return{defenders,lanes:laneSet(defenders)}}
function validStake(){let n=Number(ui.stakeInput.value);if(!Number.isFinite(n))n=100;return round2(clamp(n,1,100000))}
function rerollPack(){if(state.playing)return;state.pack=[makeRound(),makeRound(),makeRound()];renderPreview();renderScenePreview();beep(470,.04,'triangle',.025)}
function renderPreview(){ui.previewRounds.innerHTML=state.pack.map((r,i)=>`<article class="preview-card"><div class="thumbs">${r.defenders.map(d=>`<div class="thumb"><img src="${TYPES[d.type].img}" alt="${TYPES[d.type].label}"></div>`).join('')}<span class="tag">STAGE ${i+1}</span></div><div class="route-mini"><small>${r.defenders.map(d=>TYPES[d.type].en).join(' / ')}</small><b>${r.lanes.map(l=>l.odds.toFixed(2)+'×').join(' · ')}</b></div></article>`).join('')}
function updateHud(){const s=state.playing?state.stake:validStake();ui.stakeHud.textContent=money(s);ui.multiplierHud.textContent=state.multiplier.toFixed(2)+'×';ui.potentialHud.textContent=money(s*state.multiplier)}
function renderScenePreview(){ui.scene.classList.add('preview-mode');const r=state.pack[0]||makeRound();renderDefenders(r);renderRoutes(r);ui.roundLabel.textContent='PREVIEW';ui.stageCount.textContent='0 / 3'}
function renderDefenders(r){const pos=r.defenders.length===2?[33,67]:[20,50,80];ui.defendersLayer.innerHTML=r.defenders.map((d,i)=>`<div class="defender ${d.type}" style="left:${pos[i]}%"><img src="${TYPES[d.type].img}" alt=""><strong>${TYPES[d.type].en}</strong></div>`).join('')}
function renderRoutes(r){ui.routeField.innerHTML=r.lanes.map(l=>`<div class="route-path" style="left:calc(${l.x*100}% - 39px);color:${routeColor(r.lanes.indexOf(l))};transform:rotate(${(l.x-.5)*24}deg)"></div>`).join('')}
function routeColor(i){return['#44cfff','#79ff64','#df65ff','#ffb33c'][i%4]}
function startGame(){state.stake=validStake();state.round=0;state.multiplier=1;state.playing=true;state.locked=false;ui.previewPanel.classList.add('hidden');ui.resultPanel.classList.add('hidden');ui.resultPanel.classList.remove('lose');ui.scene.classList.remove('preview-mode');updateHud();startRound()}
function startRound(){const r=state.pack[state.round];state.locked=false;renderDefenders(r);renderRoutes(r);ui.roundLabel.textContent=`${state.round+1} / 3`;ui.stageCount.textContent=`${state.round} / 3`;ui.routeButtons.innerHTML=r.lanes.map((l,i)=>`<button class="route-btn" data-lane="${i}" type="button"><span class="arrow">${l.arrow}</span><strong>${l.odds.toFixed(2)}×</strong><small>${l.name}</small></button>`).join('');ui.routeButtons.querySelectorAll('button').forEach(b=>b.onclick=()=>chooseLane(+b.dataset.lane));ui.routeButtons.classList.remove('hidden');ui.timerWrap.classList.remove('hidden');ui.message.classList.add('hidden');startTimer()}
function startTimer(){clearInterval(state.timerId);state.timerStart=performance.now();const tick=()=>{if(!state.playing||state.locked)return;const left=Math.max(0,CHOICE_SECONDS-(performance.now()-state.timerStart)/1000),ratio=left/CHOICE_SECONDS;ui.timerText.textContent=left.toFixed(1);ui.timerBar.style.transform=`scaleX(${ratio})`;ui.timerWrap.querySelector('.timer-ring').style.setProperty('--progress',`${ratio*100}%`);if(left<=0)timeoutFail()};tick();state.timerId=setInterval(tick,50)}
async function chooseLane(index){if(state.locked||!state.playing)return;state.locked=true;clearInterval(state.timerId);ui.routeButtons.classList.add('hidden');ui.timerWrap.classList.add('hidden');const lane=state.pack[state.round].lanes[index];const p=clamp(RTP/lane.odds,.18,.88),success=rand()<p;ui.scene.classList.add('action');beep(190,.06,'square',.025);await playDribbleCinematic(success);ui.scene.classList.remove('action');resolveDribble(success,lane)}
async function timeoutFail(){if(state.locked)return;state.locked=true;clearInterval(state.timerId);ui.routeButtons.classList.add('hidden');ui.timerWrap.classList.add('hidden');ui.scene.classList.add('action');await playDribbleCinematic(false,true);ui.scene.classList.remove('action');resolveDribble(false,{odds:1},true)}
function resolveDribble(success,lane,timeout=false){if(success){state.multiplier=round2(state.multiplier*lane.odds);state.round++;ui.stageCount.textContent=`${state.round} / 3`;updateHud();showMessage(`BREAK THROUGH!  ${lane.odds.toFixed(2)}×`,true);successSound();burst(420,500,65,'#69dbff');setTimeout(()=>{ui.message.classList.add('hidden');if(state.round>=3)goalSequence();else startRound()},850)}else{showMessage(timeout?'TIME OUT — TACKLED!':'INTERCEPTED!',false);failSound();burst(420,570,48,'#ff546a');setTimeout(()=>finish(false),950)}}
async function goalSequence(){ui.message.classList.add('hidden');ui.scene.classList.add('action');goalSound();await playCinematic(['assets/shoot_1.png','assets/shoot_2.png','assets/shoot_3.png','assets/result.png'],['SHOOT!','','GOAL!','GOOOAL!'],'goal',560);ui.scene.classList.remove('action');burst(420,420,110,'#ffd54a');finish(true)}
function showMessage(text,good){ui.message.textContent=text;ui.message.className='message '+(good?'good':'bad')}
async function playDribbleCinematic(success,timeout=false){const frames=success?['assets/dribble_1.png','assets/dribble_2.png','assets/dribble_3.png','assets/dribble_4.png','assets/dribble_5.png','assets/success.png']:['assets/tackle_1.png','assets/tackle_2.png','assets/tackle_3.png','assets/tackle_4.png','assets/failed.png'];const titles=success?['RUN','BODY FEINT','STEP OVER','EXPLOSIVE','BREAK THROUGH','SUCCESS!']:['CHASE','LUNGE','CONTACT','FALL',timeout?'TIME OUT!':'TACKLED!'];await playCinematic(frames,titles,success?'good':'bad',success?390:450)}
async function playCinematic(frames,titles,mode,delay){ui.cinematic.classList.remove('hidden');ui.cineTitle.className='cine-title '+(mode==='bad'?'bad':mode==='goal'?'goal':'');let active=ui.frameA,next=ui.frameB;for(let i=0;i<frames.length;i++){next.src=frames[i];await preload(next);next.classList.add('active');active.classList.remove('active');ui.cineTitle.textContent=titles[i]||'';if(i===Math.floor(frames.length*.55)){ui.impactFlash.classList.remove('hit');void ui.impactFlash.offsetWidth;ui.impactFlash.classList.add('hit');beep(mode==='bad'?120:720,.05,mode==='bad'?'sawtooth':'triangle',.035)}[active,next]=[next,active];await wait(delay)}ui.cineTitle.textContent='';ui.cinematic.classList.add('hidden')}
function preload(img){return new Promise(r=>{if(img.complete)return r();img.onload=r;img.onerror=r})}const wait=ms=>new Promise(r=>setTimeout(r,ms));
function finish(won){state.playing=false;state.locked=true;clearInterval(state.timerId);ui.routeButtons.classList.add('hidden');ui.timerWrap.classList.add('hidden');const win=won?state.stake*state.multiplier:0;ui.resultPanel.classList.toggle('lose',!won);ui.resultTitle.textContent=won?'GOAL — YOU WIN!':'DRIBBLE STOPPED';ui.resultBody.textContent=won?'連續完成三次過人，射門直接判定進球。':'本局在完成三次過人前被攔截，Winning Amount 為 0。';ui.resultStake.textContent=money(state.stake);ui.resultOdds.textContent=state.multiplier.toFixed(2)+'×';ui.resultWin.textContent=money(win);ui.resultPanel.classList.remove('hidden')}
// lightweight FX layer
function burst(x,y,count,color){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(rand()-.5)*14,vy:-3-rand()*10,g:.25,life:1,s:2+rand()*6,r:rand()*6.28,vr:(rand()-.5)*.4,color:i%4?color:'#fff'})}
function fxLoop(){ctx.clearRect(0,0,840,1050);for(const p of state.particles){p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.life-=.022;p.r+=p.vr;ctx.save();ctx.globalAlpha=Math.max(0,p.life);ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=p.color;ctx.fillRect(-p.s/2,-p.s,p.s,p.s*2);ctx.restore()}state.particles=state.particles.filter(p=>p.life>0);state.raf=requestAnimationFrame(fxLoop)}
let audioCtx;function beep(freq=440,dur=.08,type='sine',gain=.03,delay=0){if(!state.sound)return;try{audioCtx||=new(AudioContext||webkitAudioContext)();const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+dur)}catch(_){}}
function successSound(){beep(540,.08,'triangle',.035);beep(760,.12,'triangle',.04,.08)}function failSound(){beep(170,.16,'sawtooth',.035);beep(90,.22,'sawtooth',.03,.1)}function goalSound(){[392,523,659,784,1046].forEach((f,i)=>beep(f,.2,'triangle',.03,i*.09))}
ui.rerollBtn.onclick=rerollPack;ui.startBtn.onclick=startGame;ui.againBtn.onclick=()=>{ui.resultPanel.classList.add('hidden');ui.previewPanel.classList.remove('hidden');state.round=0;state.multiplier=1;ui.scene.classList.add('preview-mode');updateHud();rerollPack()};ui.stakeInput.oninput=updateHud;ui.stakeMinus.onclick=()=>{ui.stakeInput.value=Math.max(1,validStake()-10);updateHud()};ui.stakePlus.onclick=()=>{ui.stakeInput.value=Math.min(100000,validStake()+10);updateHud()};ui.soundBtn.onclick=()=>{state.sound=!state.sound;ui.soundBtn.textContent=state.sound?'🔊':'🔇';if(state.sound)beep(620,.05)};
rerollPack();updateHud();fxLoop();
})();
